Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,7 +16,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        attempt: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
+        attempt: [1,2,3,4,5,6,7,8,9,10]
+        #,11,12,13,14,15,16,17,18,19,20]
     runs-on: actuated-arm64-2cpu-4gb
     steps:
       - uses: actions/checkout@v4
@@ -25,7 +26,7 @@ jobs:
 
       - name: Look into the tool cache before setup-go
         run: |
-          find /home/runner/actions-runner/_work/_tool/ -name go | grep bin || echo "go binary not found in _tool folder"
+          sudo find / -name go | grep bin || echo "go binary not found in root"
       - uses: actions/setup-go@v4
         with:
           go-version: ${{ steps.goversion.outputs.goversion }}
@@ -34,8 +35,7 @@ jobs:
 
       - name: Look into the tool cache after setup-go
         run: |
-          find /home/runner/actions-runner/_work/_tool/ -name go | grep bin  || echo "go binary not found in _tool folder"
-
+          sudo find / -name go | grep bin || echo "go binary not found in root"
       - name: Find where go was put
         run: |
           which go
